advanced/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('form', views.formKa, name='formka'),
    path('postformka', views.postFormKa, name='postformka'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('diterima', views.diterima, name='diterima'),
    path('dibatalkan', views.dibatalkan, name='dibatalkan'),
    path('detail/1/<str:id>', views.form1, name='form1'),
    path('postform1', views.postForm1, name='postform1'),
    path('detail/2/<str:id>', views.form2, name='form2'),
    path('postform2', views.postForm2, name='postform2'),
    path('delete', views.delete, name='delete')
]

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('team', views.team, name='team'),
    path('keuangan', views.keuangan, name='keuangan'),
    path('surat', views.surat, name='surat'),
    path('publikasi', views.publikasi, name='publikasi'),
    path('survei', views.survei, name='survei'),
]

penyetoran/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('form', views.formKs, name='formks'),
    path('postformks', views.postFormKs, name='postformks'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('diterima', views.diterima, name='diterima'),
    path('diterima2', views.diterima2, name='diterima2'),
    path('dibatalkan', views.dibatalkan, name='dibatalkan'),
    path('detail/1/<str:id>', views.form1, name='form1'),
    path('postform1', views.postForm1, name='postform1'),
    path('detail/2/<str:id>', views.form2, name='form2'),
    path('postform2', views.postForm2, name='postform2'),
    path('delete', views.delete, name='delete')

]

sit_bemui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('surat_keluar/', include(('surat_keluar.urls', 'sk'), namespace='sk')),
    path('reimbursement/', include(('reimbursement.urls', 'kr'), namespace='kr')),
    path('penyetoran/', include(('penyetoran.urls', 'ks'), namespace='ks')),
    path('advanced/', include(('advanced.urls', 'ka'), namespace='ka')),
    path('surat_besar/', include(('surat_besar.urls', 'sb'), namespace='sb')),
    path('backend/', include('backend.urls')),
    path('linebotsit/', include('linebotsit.urls')),
]

handler404 = "sit_bemui.views.page_not_found_view"

surat_besar/urls.py
from . import views
from django.urls import path

app_name = 'sb'

urlpatterns = [
    path('form', views.formSb, name='formsb'),
    path('postformsb', views.postFormSb, name='postformsb'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('diterima1', views.diterima_1, name='diterima1'),
    path('diterima2', views.diterima_2, name='diterima2'),
    path('diterima4', views.diterima_4, name='diterima4'),
    path('ditolak4', views.ditolak_4, name='ditolak4'),
    path('dibatalkan', views.dibatalkan, name='dibatalkan'),
    path('detail/3/<str:id>', views.form3, name='form3'),
    path('postform3', views.postForm3, name='postform3'),
    path('delete', views.delete, name='delete')
]

user/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('signup', views.signUp, name='signup'),
    path('postsignup', views.postSignUp, name='postsignup'),
    path('signin', views.signIn, name='signin'),
    path('postsignin', views.postSignIn, name='postsignin'),
    path('logout', views.logout, name='logout'),
    path('give_permission', views.give_permission, name='give_permission'),
    path('post_give_permission', views.post_give_permission, name='post_give_permission'),
    path('dashboard/<str:category>/<str:sort>', views.dashboard, name='dashboard'),
    path('dashboard_pengurus/<str:category>/<str:sort>', views.dashboard_pengurus, name='dashboard_pengurus'),
]

home/views.py
from django.shortcuts import render

# Create your views here.
def home (request):
    return render(request, 'home.html')

def team (request):
    return render(request, 'team.html')

def keuangan(request):
    return render(request, 'keuangan.html')

def surat(request):
    return render(request, 'surat.html')

def publikasi(request):
    return render(request, 'publikasi.html')
1
def survei(request):
    return render(request, 'survei.html')

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>Home</title>
<link rel="stylesheet" href="{% static 'main/css/style.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
		<div class="home-top">
			<div class="home-top-color-filter">
				<div class="only-desktop">
					<h1>Get your task done<br>By using SIT</h1>
					<p>Permudah segala urusanmu dengan Sistem Informasi Terintegrasi</p>
					{% if not request.session.uid %}
					<a href="{% url 'user:signin' %}" class="button fit-content">Login Sekarang</a>
					{% endif %}
				</div>
				<object class="only-desktop" data="{% static 'main/svg/Scrum-board-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-mobile">
					<object data="{% static 'main/svg/Scrum-board-pana.svg' %}" type="image/svg+xml"></object>
					<div class="only-mobile">
						<h1>Get your task done<br>By using SIT</h1>
						<p>Permudah segala urusanmu dengan Sistem Informasi Terintegrasi</p>
						{% if not request.session.uid %}
						<a href="{% url 'user:signin' %}" class="button fit-content">Login Sekarang</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		<div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Mind-map-pana.svg' %}" type="image/svg+xml"></object>
				<div>
					<h2>Apa Itu Sistem Informasi Terintegrasi?</h2>
					<p>Sistem Informasi Terintegrasi adalah suatu program kerja Biro Multimedia BEM UI dalam bentuk website untuk mempercepat dan mempermudah alur permintaan yang ada di internal BEM UI.</p>
				</div>
			</div>
			<div class="home-middle-middle">
				<div class="only-desktop">
					<h2>Kami menawarkan kemudahan</h2>
					<p>Misi kami adalah untuk meningkatkan efisiensi, efektifitas, dan memberikan kemudahan bagi para fungsionaris BEM UI dan jajaran dibawahnya dalam melakukan permintaan.</p>
					<ul>
						<li><p>Seluruh informasi terintegrasi dalam satu tempat<p></li>
						<li><p>Memudahkan tracking progress permintaan<p></li>
						<li><p>Meminimalisir miskomunikasi dalam proses alur permintaan<p></li>
					</ul>
				</div>
				<object data="{% static 'main/svg/Features-Overview-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-mobile">
					<h2>Kami menawarkan kemudahan</h2>
					<p>Misi kami adalah untuk meningkatkan efisiensi, efektifitas, dan memberikan kemudahan bagi para fungsionaris BEM UI dan jajaran dibawahnya dalam melakukan permintaan.</p>
					<ul>
						<li><p>Seluruh informasi terintegrasi dalam satu tempat<p></li>
						<li><p>Memudahkan tracking progress permintaan<p></li>
						<li><p>Meminimalisir miskomunikasi dalam proses alur permintaan<p></li>
					</ul>
				</div>
			</div>
			<div>
				<h1 class="home-features">Fitur Fitur</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div class="only-desktop">
								<h2>Keuangan</h2>
								<p>Butuh melakukan permintaan reimburse, advanced, dan penyetoran?</p>
							</div>
							<div class="only-mobile">
								<h2>Keuangan</h2>
							</div>
							<a href="{% url 'home:keuangan' %}" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div class="only-desktop">
								<h2>Publikasi</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media BEM UI?</p>
							</div>
							<div class="only-mobile">
								<h2>Publikasi</h2>
							</div>
							<a href="{% url 'home:publikasi' %}" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div class="only-desktop">
								<h2>Surat Menyurat</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari BEM UI?</p>
							</div>
							<div class="only-mobile">
								<h2>Surat Menyurat</h2>
							</div>
							<a href="{% url 'home:surat' %}" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div class="only-desktop">
								<h2>Survei</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
							<div class="only-mobile">
								<h2>Survei</h2>
							</div>
							<a href="{% url 'home:survei' %}" class="button fit-content">Telusuri</a>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/keuangan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>Home</title>
<link rel="stylesheet" href="{% static 'main/css/style-detail.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
        <div class="filler"></div>
        <div class="home-top">
			<div class="home-top-color-filter">
				<div>
					<h1>Keuangan</h1>
					<p>Lakukan pengajuan reimbursement, advanced, dan penyetoran kamu dengan memencet tombol di bawah ya</p>
                    <a href="{% url 'kr:formkr' %}" class="button fit-content">Ajukan Reimbursement</a>
					<a href="{% url 'ka:formka' %}" class="button fit-content">Ajukan Cash Advanced</a>
					<a href="{% url 'ks:formks' %}" class="button fit-content">Ajukan Penyetoran</a>
				</div>
				<object class="only-desktop" data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
			</div>
		</div>
        <div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Questions-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-desktop">
					<h2>Simak cara melakukan permintaan keuanganmu di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
				<div class="only-mobile">
					<h2>Simak cara melakukan permintaan keuanganmu di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
			</div>
			<div>
				<h1 class="home-features">Langkah-langkah</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Isi Form</h2>
								<p>Isi form permintaan dengan memencet tombol di bawah ini</p>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2 id="tahap-1">Masukkan data yang dibutuhkan</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media BEM UI?</p>
							</div>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Pantau progress permintaan</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari BEM UI?</p>
							</div>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Selesai</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/publikasi.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>Home</title>
<link rel="stylesheet" href="{% static 'main/css/style-detail.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
        <div class="filler"></div>
        <div class="home-top">
			<div class="home-top-color-filter">
				<div>
					<h1>Publikasi</h1>
					<p>Lakukan pengajuan publikasi konten kamu di kanal media BEM UI dengan memencet tombol di bawah ya</p>
                    <a href="https://www.sipbemui.xyz/" class="button fit-content">Gunakan SIP - Pindah ke SIP</a>
				</div>
				<object class="only-desktop" data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
			</div>
		</div>
        <div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Questions-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-desktop">
					<h2>Simak cara melakukan permintaan publikasi di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
				<div class="only-mobile">
					<h2>Simak cara melakukan permintaan publikasi di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
			</div>
			<div>
				<h1 class="home-features">Langkah-langkah</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Isi Form</h2>
								<p>Isi form permintaan dengan memencet tombol di bawah ini</p>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2 id="tahap-1">Masukkan data yang dibutuhkan</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media BEM UI?</p>
							</div>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Pantau progress permintaan</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari BEM UI?</p>
							</div>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Selesai</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/surat.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>Home</title>
<link rel="stylesheet" href="{% static 'main/css/style-detail.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
        <div class="filler"></div>
        <div class="home-top">
			<div class="home-top-color-filter">
				<div>
					<h1>Surat Menyurat</h1>
					<p>Lakukan pengajuan tanda tangan untuk kepentingan surat menyurat kamu dengan memencet tombol di bawah ya</p>
                    <a href="{% url 'sk:formsk' %}" class="button fit-content">Ajukan surat</a>
					<a href="{% url 'sb:formsb' %}" class="button fit-content">Pengajuan LPJ, SPK, MoU</a>
{#					<a href="" class="button fit-content">Ajukan sertifikat</a>#}

				</div>
				<object class="only-desktop" data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
			</div>
		</div>
        <div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Questions-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-desktop">
					<h2>Simak cara melakukan permintaan surat menyurat di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
				<div class="only-mobile">
					<h2>Simak cara melakukan permintaan surat menyurat di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
			</div>
			<div>
				<h1 class="home-features">Langkah-langkah</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Isi Form</h2>
								<p>Isi form permintaan dengan memencet tombol di bawah ini</p>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2 id="tahap-1">Masukkan data yang dibutuhkan</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media BEM UI?</p>
							</div>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Pantau progress permintaan</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari BEM UI?</p>
							</div>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Selesai</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/survei.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>Home</title>
<link rel="stylesheet" href="{% static 'main/css/style-detail.css' %}">
  <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
	<div class="content-home">
        <div class="filler"></div>
        <div class="home-top">
			<div class="home-top-color-filter">
				<div>
					<h1>Survei</h1>
					<p>Lakukan pengajuan survei untuk kepentingan penelitian dan pengembangan kamu dengan memencet tombol di bawah ya</p>
                    <a href="" class="button fit-content">Ajukan permintaan</a>
				</div>
				<object class="only-desktop" data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
			</div>
		</div>
        <div class="home-middle">
			<div class="home-middle-top">
				<object data="{% static 'main/svg/Questions-pana.svg' %}" type="image/svg+xml"></object>
				<div class="only-desktop">
					<h2>Simak cara melakukan permintaan survei di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
				<div class="only-mobile">
					<h2>Simak cara melakukan permintaan survei di bawah ini!</h2>
					<p>Kalian masih bingung cara menggunakan website SIT? Yuk, Kami ajarin!</p>
				</div>
			</div>
			<div>
				<h1 class="home-features">Langkah-langkah</h1>
				<div class="home-middle-bottom">
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Piggy-bank-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Isi Form</h2>
								<p>Isi form permintaan dengan memencet tombol di bawah ini</p>
							</div>
							<a href="" class="button fit-content">Telusuri</a>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Content-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2 id="tahap-1">Masukkan data yang dibutuhkan</h2>
								<p>Butuh melakukan permintaan publikasi di kanal media BEM UI?</p>
							</div>
						</div>
					 </div>
					<div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Mail-sent-pana.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Pantau progress permintaan</h2>
								<p>Ingin meminta persetujuan dan tanda tangan dari BEM UI?</p>
							</div>
						</div>
					 </div>
					 <div class="home-card-container">
						<div class="home-card-top-blank"></div>
						<object data="{% static 'main/svg/Customer-Survey-amico.svg' %}" type="image/svg+xml"></object>
						<div class="home-card">
							<div>
								<h2>Selesai</h2>
								<p>Membutuhkan survei untuk kepentingan penelitian dan pengembangan?</p>
							</div>
						</div>
					 </div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

home/templates/team.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'main/css/team-style.css' %}">
    <script type="application/javascript" src="{% static 'main/js/script.js' %}"></script>
{% endblock meta %}

{% block content %}
    <div class="main">
      <div class="item">
          <img src="{% static 'base/img/MDT_SIT.png' %}" style="width: 35rem">
      </div>
      <div class="item right-section">
        <h2 class="secondary-title">Who we are</h2>
        <p class="description">We built systems, websites, and mobile applications to elevate and enhance productivity in Badan Eksekutif Mahasiswa UI</p>
      </div>
    </div>


    <div class="team-members">

      <div class="team member-1">
        <img id="img-1" src="{% static 'main/img/Mika2.JPG' %}" alt="Mika Suryofakhri Rahwono">
        <span class="position">Project Owner - Full Stack Developer</span>
        <p class="name">Mika Suryofakhri Rahwono</p>
        <p>Fakultas Ilmu Komputer - UI</p>
      </div>

    </div>
{% endblock content %}