home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('team', views.team, name='team'),
    path('keuangan', views.keuangan, name='keuangan'),
    path('surat', views.surat, name='surat'),
    path('publikasi', views.publikasi, name='publikasi'),
    path('survei', views.survei, name='survei'),
]

sit_bemui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('surat_keluar/', include(('surat_keluar.urls', 'sk'), namespace='sk')),
    path('reimbursement/', include(('reimbursement.urls', 'kr'), namespace='kr')),
    path('penyetoran/', include(('penyetoran.urls', 'ks'), namespace='ks')),
    path('advanced/', include(('advanced.urls', 'ka'), namespace='ka')),
    path('surat_besar/', include(('surat_besar.urls', 'sb'), namespace='sb')),
    path('backend/', include('backend.urls')),
    path('linebotsit/', include('linebotsit.urls')),
]

handler404 = "sit_bemui.views.page_not_found_view"

user/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('signup', views.signUp, name='signup'),
    path('postsignup', views.postSignUp, name='postsignup'),
    path('signin', views.signIn, name='signin'),
    path('postsignin', views.postSignIn, name='postsignin'),
    path('logout', views.logout, name='logout'),
    path('give_permission', views.give_permission, name='give_permission'),
    path('post_give_permission', views.post_give_permission, name='post_give_permission'),
    path('dashboard/<str:category>/<str:sort>', views.dashboard, name='dashboard'),
    path('dashboard_pengurus/<str:category>/<str:sort>', views.dashboard_pengurus, name='dashboard_pengurus'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'base/img/favicon.png' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="application/javascript" src="{% static 'base/js/script.js' %}"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
	<header {% if '/' == request.path %}class="header-transparent"{% else %}class="header-white"{% endif %}>
        <a href="{% url 'home:home' %}" class="logo"><img src="{% static 'base/img/logo-sit.png' %}" style="width:8.75rem; height:3.5rem;"></a>
        <input type="checkbox" class="nav-toggle" id="nav-toggle">

        <nav>
            <ul>
                <li><a href="{% url 'home:keuangan' %}">Keuangan</a></li>
                <li><a href="{% url 'home:publikasi' %}">Publikasi</a></li>
                <li><a href="{% url 'home:surat' %}">Surat</a></li>
{#                <li><a href="{% url 'home:survei' %}">Survei</a></li>#}
                {% if request.session.admin %}
                    <li><a href="{% url 'user:give_permission' %}">Give Permission</a></li>
                    <li><a href="{% url 'user:signup' %}">SignUp</a></li>
                {% endif %}
                {% if not request.session.uid %}
                <li class="nav-only-desktop">
                    <a href="{% url 'user:signin' %}" class="button fit-content" style="height: fit-content; margin: 0; padding: 0.6em 1em;">Masuk</a>
                </li>
                <div class="nav-dropdown-buttons nav-only-mobile">
                    <a href="{% url 'user:signin' %}" class="nav-only-mobile button btn-dashboard">
                        Masuk
                    </a>
                </div>
                {% endif %}
                {% if request.session.uid %}
                <li class="nav-only-desktop">
                    <a href="{% url 'user:dashboard' 'home' 'home' %}" class="button fit-content" style="height: fit-content; margin: 0; padding: 0.6em 1em;">Dashboard</a>
                </li>
                <div class="nav-dropdown-buttons nav-only-mobile">
                    <a href="{% url 'user:dashboard' 'home' 'home' %}" class="nav-only-mobile button btn-dashboard">
                        Dashboard
                    </a>
                </div>
                {% endif %}
            </ul>
        </nav>

        <label for="nav-toggle" class="nav-toggle-label" id="nav-toggle-label"><span></span></label>

    </header>

    <div class="content-container">
      	{% block content %}
        {% endblock content %}
	</div>

    <footer>
        <div class="footer-upper">
            <div class="footer1">
                <a href="{% url 'home:home' %}"><img src="{% static 'base/img/logo-sit-footer.png' %}" style="width:12.5rem; height:5rem;"></a>
            </div>

            <div class="footer2">
                <a href="{% url 'home:team' %}"><img src="{% static 'base/img/MDT_LOGO.png' %}" style="width:12.5rem; height:5rem;"></a>
            </div>

            <div class="footer3 nav-only-mobile">
                <p>
                    <svg width="24" height="24" viewBox="0 0 24 24">
                        <use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
                    </svg>
                    @ 2022 - Badan Eksekutif Mahasiswa UI - Biro Multimedia
                </p>
            </div>
        </div>

        <div class="footer-middle nav-only-desktop">
            <div class="footer1-middle footer-mid">
                <a href="{% url 'home:keuangan' %}"><strong>Keuangan</strong></a>
                <a href="{% url 'home:keuangan' %}"><p>Reimbursement</p></a>
                <a href="{% url 'home:keuangan' %}"><p>Advanced</p></a>
                <a href="{% url 'home:keuangan' %}"><p>Penyetoran</p></a>
                <br>
                <a href="{% url 'home:publikasi' %}"><strong>Publikasi</strong></a>
                <a href="{% url 'home:publikasi' %}"><p>Publikasi</p></a>
            </div>
            <div class="footer2-middle footer-mid">
                <a href="{% url 'home:surat' %}"><strong>Surat Menyurat</strong></a>
                <a href="{% url 'home:surat' %}"><p>LPJ, SPK, MoU</p></a>
{#                <a href="{% url 'home:surat' %}"><p>BEM UI</p></a>#}
{#                <a href="{% url 'home:surat' %}"><p>sertifikat</p></a>#}
                <br>
{#                <a href="{% url 'home:survei' %}"><strong>Survei</strong></a>#}
{#                <a href="{% url 'home:survei' %}"><p>Survei</p></a>#}
            </div>
        </div>

        <div class="footer-bottom nav-only-desktop">
            <div>
                <svg width="24" height="24" viewBox="0 0 24 24">
                    <use href="{% static 'base/svg/base-sprite-sheet.svg' %}#copyright-logo"></use>
                </svg>
                <p>2022 - Badan Eksekutif Mahasiswa UI - Biro Multimedia</p>
            </div>
        </div>
    </footer>
</body>

</html>