home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('team', views.team, name='team'),
    path('keuangan', views.keuangan, name='keuangan'),
    path('surat', views.surat, name='surat'),
    path('publikasi', views.publikasi, name='publikasi'),
    path('survei', views.survei, name='survei'),
]

reimbursement/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('form', views.formKr, name='formkr'),
    path('postformkr', views.postFormKr, name='postformkr'),
    path('detail/<str:id>', views.detail, name='detail'),
    path('diterima', views.diterima, name='diterima'),
    path('dibatalkan', views.dibatalkan, name='dibatalkan'),
    path('detail/1/<str:id>', views.form1, name='form1'),
    path('postform1', views.postForm1, name='postform1'),
    path('detail/2/<str:id>', views.form2, name='form2'),
    path('postform2', views.postForm2, name='postform2'),
    path('delete', views.delete, name='delete')
]

sit_bemui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('surat_keluar/', include(('surat_keluar.urls', 'sk'), namespace='sk')),
    path('reimbursement/', include(('reimbursement.urls', 'kr'), namespace='kr')),
    path('penyetoran/', include(('penyetoran.urls', 'ks'), namespace='ks')),
    path('advanced/', include(('advanced.urls', 'ka'), namespace='ka')),
    path('surat_besar/', include(('surat_besar.urls', 'sb'), namespace='sb')),
    path('backend/', include('backend.urls')),
    path('linebotsit/', include('linebotsit.urls')),
]

handler404 = "sit_bemui.views.page_not_found_view"

reimbursement/views.py
import json

from django.http import Http404
from django.shortcuts import render, redirect
from backend.CRUD.crud_kr import kr_create, kr_read, kr_update_0, kr_update_1, kr_update_2, kr_delete
from backend.CRUD.crud_user import user_read
from backend.constants.links import links_keuangan
from backend.misc import firebase_init, getPhoto
from backend.constants.admins import reimbursement_admin, reimbursement_admin2

# Initialize Firebase Database
fauth = firebase_init


# ---------------------
# Form Request Reimbursement
# --------------------
def formKr(request):
    try:
        if (request.session['uid']):
            if (fauth.get_account_info(request.session['uid'])):
                return render(request, 'reimbursement/form_kr.html', {
                    'template': links_keuangan['Reimbursement']
                })
            else:
                return redirect("/user/logout")
    except:
        return redirect("/user/signin")


def postFormKr(request):
    judul = request.POST.get("judul")
    nama_kegiatan = request.POST.get("nama_kegiatan")
    deskripsi = request.POST.get("deskripsi")
    bank = request.POST.get("bank")
    norek = request.POST.get("norek")
    anrek = request.POST.get("anrek")
    voucher = request.POST.get("link_voucher")
    nominal = request.POST.get("nominal")
    photos = request.POST.get("uploadFiles")
    photos = json.loads(photos)
    print(photos)

    # Upload data to firebase
    if photos[0]["successful"]:
        photos_meta = []
        for i in photos[0]["successful"]:
            photos_meta.append(i["meta"]["id_firebase"])
        message = kr_create(request, judul, nama_kegiatan, deskripsi, bank, norek, anrek, voucher, nominal, photos_meta)
        if message != "terjadi error":
            return redirect("/reimbursement/detail/" + message)
        else:
            message = "Gagal Upload"
            return redirect('kr:formkr')
    else:
        message = "Gagal Upload"
        return redirect("user:logout")


# ---------------------
# Detail Reimbursement
# --------------------
def detail(request, id):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                data_detail = kr_read(id)
                user = user_read(user_session['users'][0]['localId'])
                if (data_detail != []):
                    if (user["id"] == data_detail["idBirdep"] or user['birdeptim'] in reimbursement_admin2["admin"]):
                        # Get Photos Bukti Pembayaran
                        data_photo = []
                        for photo in data_detail["bukti_pembayaran"]:
                            url = getPhoto.getPhoto(photo)
                            data_photo.append(url)
                        # Get Voucher Files
                        try:
                            url = getPhoto.getPhoto(data_detail["token_voucher"][0])
                            voucher = url
                        except:
                            voucher = ""
                        # Get Bukti Transfer
                        try:
                            url = getPhoto.getPhoto(data_detail["bukti_transfer"][0])
                            transfer = url
                        except:
                            transfer = ""
                        print(data_detail)
                        print(reimbursement_admin)
                        print(data_photo)
                        return render(request, 'reimbursement/kr_details.html', {
                            'data': data_detail,
                            'user': user,
                            'admin': reimbursement_admin,
                            'id': id,
                            'photos': data_photo,
                            'voucher': voucher,
                            'transfer': transfer
                        })
                    else:
                        raise Http404
                else:
                    return redirect("/user/logout")
    except:
        return redirect("/user/signin")


# ---------------------
# Form Tahap 0 Reimbursement
# --------------------
def diterima(request):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                user = user_read(user_session['users'][0]['localId'])
                if (user['birdeptim'] in reimbursement_admin2["tahap1"]):
                    print('masuk')
                    id_request = request.POST.get("id_request")
                    kr_update_0(request, id_request, 1)
                    return redirect('kr:detail', id=id_request)
            else:
                redirect('user:logout')
    except:
        redirect('user:signin')


def dibatalkan(request):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                user = user_read(user_session['users'][0]['localId'])
                if (user['birdeptim'] in reimbursement_admin2["tahap1"]):
                    id_request = request.POST.get("id_request")
                    kr_update_0(request, id_request, -1)
                    return redirect('kr:detail', id=id_request)
            else:
                redirect('user:logout')
    except:
        redirect('user:signin')


# ---------------------
# Form Tahap 1 Reimbursement
# --------------------
def form1(request, id):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if(user_session):
                user = user_read(user_session['users'][0]['localId'])
                data_detail = kr_read(id)
                if (user['birdeptim'] in reimbursement_admin2["tahap1"]):
                    if (data_detail["tahapan"] == 1):
                        return render(request, 'reimbursement/tahap1_form.html', {"id": id})
                    else:
                        return redirect("/reimbursement/detail/" + id)
                else:
                    return redirect("/reimbursement/detail/" + id)
            else:
                return redirect("/user/logout")
        else:
            return redirect("/user/signin")
    except:
        return redirect("/")


def postForm1(request):
    diterima = request.POST.get("diterima")
    voucher = request.POST.get("uploadFiles")
    id_request = request.POST.get("id_request")
    voucher = json.loads(voucher)
    print(voucher)

    # Upload data to firebase
    try:
        if voucher[0]["successful"] :
            print("masuk")
            voucher_meta = []
            voucher_meta.append(voucher[0]["successful"][0]["meta"]["id_firebase"])
            message = kr_update_1(request, id_request, diterima, voucher_meta)
            print(message)
            if message != "terjadi error":
                return redirect("/reimbursement/detail/" + id_request)
            else:
                message = "Gagal Upload"
                return redirect("/reimbursement/detail/" + id_request)
        else:
            message = "Gagal Upload"
            return redirect("/reimbursement/detail/" + id_request)
    except:
        return redirect("/")


# ---------------------
# Form Tahap 2 Reimbursement
# --------------------
def form2(request, id):
    try:
        if (request.session['uid']):
            print("masuk")
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                user = user_read(user_session['users'][0]['localId'])
                data_detail = kr_read(id)
                if (user['birdeptim'] in reimbursement_admin2["tahap2"]):
                    if (data_detail["tahapan"] == 2):
                        return render(request, 'reimbursement/tahap2_form.html', {"id": id})
                    else:
                        return redirect("/reimbursement/detail/" + id)
                else:
                    return redirect("/reimbursement/detail/" + id)
            else:
                return redirect("/user/logout")
        else:
            return redirect("/user/signin")
    except:
        return redirect("/")


def postForm2(request):
    bukti = request.POST.get("uploadFiles")
    id_request = request.POST.get("id_request")
    bukti = json.loads(bukti)
    print(bukti)

    # Upload data to firebase
    try:
        if bukti[0]["successful"]:
            bukti_meta = []
            bukti_meta.append(bukti[0]["successful"][0]["meta"]["id_firebase"])
            message = kr_update_2(request, id_request, bukti_meta)
            if message != "terjadi error":
                return redirect("/reimbursement/detail/" + id_request)
            else:
                message = "Gagal Upload"
                return redirect("/reimbursement/detail/" + id_request)
        else:
            message = "Gagal Upload"
            return redirect("/reimbursement/detail/" + id_request)
    except:
        return redirect("/")


# ---------------------
# Delete Request
# --------------------
def delete(request):
    try:
        if (request.session['uid']):
            user_session = fauth.get_account_info(request.session['uid'])
            if (user_session):
                user = user_read(user_session['users'][0]['localId'])
                if (user['birdeptim'] in reimbursement_admin2["admin"]):
                    print('masuk')
                    id_request = request.POST.get("id_request")
                    print(id_request)
                    data = kr_delete(id_request)
                    print(data)
                    return redirect('../user/dashboard_pengurus/reimbursement/semua')
            else:
                return redirect('user:logout')
    except:
        return redirect('user:signin')

reimbursement/templates/reimbursement/form_kr.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Form Reimbursement</title>
    <link rel="stylesheet" href="{% static 'reimbursement/css/style.css' %}"/>
    <link href="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.css" rel="stylesheet"/>
{% endblock meta %}

{% block content %}
    <div class="content-root">
        <div class="form-root">
            <h1 id="judul-form">Form Pengajuan Reimbursement</h1>
            <section>
                <form action="postformkr" method="post" id="form">
                    {% csrf_token %}
                    <label for="judul" >Judul</label>
                    <input type="text" id="judul" name="judul" placeholder="Judul Permintaan..."> <br/>

                    <label for="kegiatan" >Nama Kegiatan</label>
                    <input type="text" id="kegiatan" name="nama_kegiatan" placeholder="Nama Kegiatan..."><br/>

                    <label for="deskripsi">Deskripsi Singkat Kegiatan</label>
                    <input type="text" id="deskripsi" name="deskripsi" placeholder="Deksripsi Singkat..."><br/>

                    <label for="rekening">Nomor Rekening</label>
                    <input type="number" id="rekening" name="norek" placeholder="Nomor Rekening..."><br/>

                    <label for="atas-nama">Atas Nama Rekening</label>
                    <input type="text" id="atas-nama" name="anrek" placeholder="Atas Nama Rekening..."><br/>

                    <label for="bank">Nama Bank Rekening</label>
                    <input type="text" id="bank" name="bank" placeholder="Nama bank rekening anda..."><br/>

                    <a href="{{ template }}" target="_blank"><p>Template Voucher Penarikan Kas</p></a>

                    <label for="link-docs">Link Docs Voucher Pengajuan</label>
                    <input type="url" id="link-docs" name="link_voucher" placeholder="Link Docs Voucher..."><br/>

                    <label for="nominal">Nominal Reimburse</label>
                    <input type="number" id="nominal" name="nominal" placeholder="Nominal Uang Reimburse..."><br/>

                    <label class="control-label">Upload Bukti Pembayaran</label>
                    <div class="uppy" id="drag-drop-area"></div>

                    <div class="filler"></div>

                    <input name="uploadFiles" type="hidden">

                </form>

                <button type="button" class="button" id="submitbutton">Ajukan</button>

                <div class="filler"></div>

                <!-- Script upload ke Bukti Pembayaran-->
                <script src="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.js"></script>
                <script>
                    var uppy = new Uppy.Core()

                    uppy.on('file-added', (file) => {
                        uppy.setFileMeta(file.id, {
                            id_firebase: "KEUANGAN_REIMBURSE/BUKTI_PEMBAYARAN/" + uuidv4(),
                        })
                    })
                    uppy.use(Uppy.XHRUpload, {
                        endpoint: '{% url "upload_photo" %}',
                        headers: {'X-CSRFToken':"{{csrf_token}}"},
                        formData: true,
                        fieldName: 'file'
                    })
                    uppy.use(Uppy.Dashboard, {
                        inline: true,
                        target: '#drag-drop-area',
                        proudlyDisplayPoweredByUppy:false,
                        showProgressDetails:true,
                        doneButtonHandler: null,
                        hideUploadButton: true,
                    })
                    uppy.on('complete', (result) => {
                        console.log('Upload complete! We’ve uploaded these files:', result.successful)
                    })
                    uppy.use(Uppy.Form, {
                        target: "#form",
                        resultName: 'uploadFiles',
                        getMetaFromForm: false,
                        addResultToForm: true,
                        submitOnSuccess: true,
                        triggerUploadOnSubmit: false,
                    })
                </script>
                <script type="application/javascript" src="{% static 'reimbursement/js/scripts.js' %}"></script>
                <script src="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.js"></script>
            </section>
        </div>
    <object class="object only-desktop" data="{% static 'reimbursement/svg/Topup-credit-bro.svg' %}" type="image/svg+xml"></object>
    </div>
{% endblock content %}

reimbursement/templates/reimbursement/kr_details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Detail Request</title>
    <link rel="stylesheet" href="{% static 'reimbursement/css/style-details.css' %}">
{% endblock meta %}

{% block content %}
    <div class="content-root">
		<a href="{% url 'home:keuangan' %}" id="button-kembali">&lt Kembali</a>
        {% if user.birdeptim in admin.admin %}
            <div class="button-del" onclick="document.getElementById('modal_del').style.display='block'">
            <svg enable-background="new 0 0 32 32" height="1em" id="Layer_1" version="1.1" viewBox="0 0 32 32" width="1em" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="trash"><path clip-rule="evenodd" d="M29.98,6.819c-0.096-1.57-1.387-2.816-2.98-2.816h-3v-1V3.001   c0-1.657-1.344-3-3-3H11c-1.657,0-3,1.343-3,3v0.001v1H5c-1.595,0-2.885,1.246-2.981,2.816H2v1.183v1c0,1.104,0.896,2,2,2l0,0v17   c0,2.209,1.791,4,4,4h16c2.209,0,4-1.791,4-4v-17l0,0c1.104,0,2-0.896,2-2v-1V6.819H29.98z M10,3.002c0-0.553,0.447-1,1-1h10   c0.553,0,1,0.447,1,1v1H10V3.002z M26,28.002c0,1.102-0.898,2-2,2H8c-1.103,0-2-0.898-2-2v-17h20V28.002z M28,8.001v1H4v-1V7.002   c0-0.553,0.447-1,1-1h22c0.553,0,1,0.447,1,1V8.001z" fill="#f00000" fill-rule="evenodd"/><path clip-rule="evenodd" d="M9,28.006h2c0.553,0,1-0.447,1-1v-13c0-0.553-0.447-1-1-1H9   c-0.553,0-1,0.447-1,1v13C8,27.559,8.447,28.006,9,28.006z M9,14.005h2v13H9V14.005z" fill="#f00000" fill-rule="evenodd"/><path clip-rule="evenodd" d="M15,28.006h2c0.553,0,1-0.447,1-1v-13c0-0.553-0.447-1-1-1h-2   c-0.553,0-1,0.447-1,1v13C14,27.559,14.447,28.006,15,28.006z M15,14.005h2v13h-2V14.005z" fill="#f00000" fill-rule="evenodd"/><path clip-rule="evenodd" d="M21,28.006h2c0.553,0,1-0.447,1-1v-13c0-0.553-0.447-1-1-1h-2   c-0.553,0-1,0.447-1,1v13C20,27.559,20.447,28.006,21,28.006z M21,14.005h2v13h-2V14.005z" fill="#f00000" fill-rule="evenodd"/></g></svg>
            <span style="color: red">Delete</span>
            </div>
        {% endif %}

        <div id="modal_del" class="modal">
          <span onclick="document.getElementById('modal_del').style.display='none'" class="close" title="Close Modal">×</span>
          <form class="modal-content-del" action="../delete" method="post">
              {% csrf_token %}
              <input name="id_request" type="hidden" value={{ id }}>
              <div class="container">
              <h1>Delete Permohonan</h1>
              <p>Apakah anda yakin untuk menghapus permohonan?</p>

              <div class="clearfix">
                <button type="button" onclick="document.getElementById('modal_del').style.display='none'" class="modal-button-del cancelbtn">Cancel</button>
                <button type="submit" onclick="document.getElementById('modal_del').style.display='none'" class="modal-button-del deletebtn">Delete</button>
              </div>
            </div>
          </form>
        </div>

		<div class="details-judul">
			<h2>{{data.judul}}</h2> <br>
			<h2>({{data.idPermintaan}})</h2>
		</div>
		<svg class="BarOuter" viewBox="0 0 2728 478" fill="#EBEBEB" xmlns="http://www.w3.org/2000/svg" style="--progress-bar: {% if data.tahapan != 3 %} {{data.tahapan}} {% else %} 3.45 {% endif %}">
			<g id="BarOut">
				<g id="OuterLayer">
					<rect id="Rectangle 1" x="77" y="216" width="2583" height="66" rx="33" stroke="#144B84" stroke-width="5"/>
					<circle id="Ellipse7" cx="480.5" cy="249.5" r="116.5" fill="#EBEBEB" stroke="#144B84" stroke-width="5"/>
					<text fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="54" letter-spacing="0em"><tspan x="350" y="450">Checking</tspan></text>
					<circle id="Ellipse8" cx="1100.5" cy="249.5" r="116.5" fill="#EBEBEB" stroke="#144B84" stroke-width="5"/>
					<text fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="54" letter-spacing="0em"><tspan x="850" y="450">Creating Voucher</tspan></text>
					<circle id="Ellipse9" cx="1700.5" cy="249.5" r="116.5" fill="#EBEBEB" stroke="#144B84" stroke-width="5"/>
					<text fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="54" letter-spacing="0em"><tspan x="1590" y="450">Transfer</tspan></text>
					<circle id="Ellipse10" cx="2300.5" cy="249.5" r="116.5" fill="#EBEBEB" stroke="#144B84" stroke-width="5"/>
					<text fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="54" letter-spacing="0em"><tspan x="2190" y="450">Finished</tspan></text>
				</g>
				<g id="Bar">
					<mask id="mask0" mask-type="alpha" maskUnits="userSpaceOnUse" x="72" y="128" width="2993" height="243">
						<g id="Mask">
							<circle id="Ellipse1" cx="480.5" cy="249.5" r="116.5" fill="#C4C4C4" stroke="#144B84" stroke-width="10"/>
							<circle id="Ellipse2" cx="1100.5" cy="249.5" r="116.5" fill="#C4C4C4" stroke="#144B84" stroke-width="10"/>
							<circle id="Ellipse3" cx="1700.5" cy="249.5" r="116.5" fill="#C4C4C4" stroke="#144B84" stroke-width="10"/>
							<circle id="Ellipse4" cx="2300.5" cy="249.5" r="116.5" fill="#C4C4C4" stroke="#144B84" stroke-width="10"/>
							<rect id="Rectangle 3" x="72" y="211" width="2593" height="76" rx="38" fill="#C4C4C4"/>
						</g>
					</mask>
					<g mask="url(#mask0)">
						<rect id="Filling" x="-3250" y="133" width="3233" height="233" rx="35" fill="#144B84" stroke="#144B84" stroke-width="10"/>
					</g>
				</g>
				<g id="Numbers">
					<text {% if data.tahapan >= 0 %}class="white-text"{% endif %} id="one" fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="144" letter-spacing="0em"><tspan x="450.203" y="298.82">1</tspan></text>
					<text {% if data.tahapan >= 1 %}class="white-text"{% endif %} id="two" fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="144" letter-spacing="0em"><tspan x="1050.742" y="298.82">2</tspan></text>
					<text {% if data.tahapan >= 2 %}class="white-text"{% endif %} id="three" fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="144" letter-spacing="0em"><tspan x="1660" y="298.82">3</tspan></text>
					<text {% if data.tahapan >= 3 %}class="white-text"{% endif %} id="four" fill="#144B84" xml:space="preserve" style="white-space: pre" font-family="Poppins" font-size="144" letter-spacing="0em"><tspan x="2250" y="298.82">4</tspan></text>
				</g>
			</g>
		</svg>

		<div class="details-info detail-only-desktop">
			<h1>Data Pesanan</h1>
			<br>
			<div class="row">
				<div class="column">
					<h3>Pemohon</h3>
					<p>{{data.nama_birdep}}</p>
					<h3>Nama Kegiatan</h3>
					<p>{{data.nama_kegiatan}}</p>
					<h3>Deskripsi Kegiatan</h3>
					<p>{{data.deskripsi}}</p>
				</div>
				<div class="column">
					<h3>Nominal Reimbursement</h3>
					<p class="currency">{{data.total_nominal}}</p>
					<h3>Data Rekening</h3>
					<p>{{data.AN_rekening}}<br>{{data.nomor_rekening}}<br>{{data.bank}}</p>
					<p></p>
					<h3>Voucher</h3>
					<a href="{{data.link_voucher}}" target="_blank">Voucher</a>
				</div>
			</div>
		</div>
		<div class="details-info only-mobile">
			<h1>Data Pesanan</h1>
			<br>
			<h3>Pemohon</h3>
			<p>{{data.nama_birdep}}</p>
			<h3>Nama Kegiatan</h3>
			<p>{{data.nama_kegiatan}}</p>
			<h3>Deskripsi Kegiatan</h3>
			<p>{{data.deskripsi}}</p>
			<h3>Nominal Reimbursement</h3>
			<p class="currency">{{data.total_nominal}}</p>
			<h3>Data Rekening</h3>
			<p>{{data.AN_rekening}}</p>
			<p>{{data.nomor_rekening}}</p>
			<h3>Voucher</h3>
			<a href="{{data.link_voucher}}" target="_blank" rel="noopener noreferrer">{{data.link_voucher}}</a>
		</div>

		<div class="bukti-pembayaran">
			<h3>Bukti Pembayaran</h3>
			{% for photo in photos %}
			<img class="bukti-image" src='{{ photo }}'/>
			<div class="modal">
				<span class="close">&times;</span>
				<img class="modal-content" src="{{photo}}">
			</div>
			{% endfor %}
		</div>

		{% if voucher != "" %}
		<div class="voucher">
			<h3>Voucher</h3>
			<embed src="{{voucher}}" class="voucher"/>
		</div>
		{% endif %}

		{% if transfer != "" %}
		<div class="transfer">
			<h3>Bukti Transfer</h3>
			<img class="bukti-image" src='{{ transfer }}'/>
			<div class="modal">
				<span class="close">&times;</span>
				<img class="modal-content" src="{{transfer}}">
			</div>
		</div>
		{% endif %}

		<div class="button-outer">
			{% if user.birdeptim in admin.tahap1 and data.tahapan == 0 %}
			<form action="../dibatalkan" method="post">
				{% csrf_token %}
				<input name="id_request" type="hidden" value={{ id }}>
				<button class="button-sec" type="submit">Batalkan</button>
			</form>
			<form action="../diterima" method="post">
				{% csrf_token %}
				<input name="id_request" type="hidden" value={{ id }}>
				<button class="button" type="submit">Terima</button>
			</form>

			{% elif user.birdeptim in admin.tahap1 and data.tahapan == 1 %}
				<a href="{% url 'kr:form1' id=id %}" class="button">Masukkan berkas</a>
			{% elif user.birdeptim in admin.tahap2 and data.tahapan == 2 %}
				<a href="{% url 'kr:form2' id=id %}" class="button">Masukkan bukti transfer</a>
			{% endif %}
		</div>
	</div>
    <script type="application/javascript" src="{% static 'reimbursement/js/scripts-details.js' %}"></script>
{% endblock content %}

reimbursement/templates/reimbursement/tahap1_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Form Voucher</title>
    <link rel="stylesheet" href="{% static 'reimbursement/css/style.css' %}"/>
    <link href="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.css" rel="stylesheet"/>
{% endblock meta %}

{% block content %}
    <div class="content-root">
        <div class="form-root">
            <h1 id="judul-form">Form Pengiriman Voucher</h1>
            <section>
                <form action="../../postform1" method="post" id="form">
                    {% csrf_token %}
                    <label for="diterima">Jumlah Diterima</label>
                    <input type="number" id="diterima" name="diterima" placeholder="Nominal Uang Diterima..."><br/>

                    <label class="control-label">Upload Voucher</label>
                    <div class="uppy" id="drag-drop-area"></div>

                    <input name="uploadFiles" type="hidden">
                    <input name="id_request" type="hidden" value={{ id }}>
                </form>

                <button type="button" class="button" id="submitbutton">Submit</button>

                <div class="filler"></div>

                <!-- Script upload ke Voucher-->
                <script src="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.js"></script>
                <script>
                    var uppy = new Uppy.Core({
                        restrictions: {
                            maxNumberOfFiles: 1,
                            allowedFileTypes: [".pdf"],
                      },
                    })

                    uppy.on('file-added', (file) => {
                        uppy.setFileMeta(file.id, {
                            id_firebase: "KEUANGAN_REIMBURSE/VOUCHER/" + uuidv4(),
                        })
                    })
                    uppy.use(Uppy.XHRUpload, {
                        endpoint: '{% url "upload_photo" %}',
                        headers: {'X-CSRFToken':"{{csrf_token}}"},
                        formData: true,
                        fieldName: 'file'
                    })
                    uppy.use(Uppy.Dashboard, {
                        inline: true,
                        target: '#drag-drop-area',
                        proudlyDisplayPoweredByUppy:false,
                        showProgressDetails:true,
                        doneButtonHandler: null,
                        hideUploadButton: true,
                    })
                    uppy.on('complete', (result) => {
                        console.log('Upload complete! We’ve uploaded these files:', result.successful)
                    })
                    uppy.use(Uppy.Form, {
                        target: "#form",
                        resultName: 'uploadFiles',
                        getMetaFromForm: false,
                        addResultToForm: true,
                        submitOnSuccess: true,
                        triggerUploadOnSubmit: false,
                    })
                </script>
                <script src="https://releases.transloadit.com/uppy/v2.9.4/uppy.min.js"></script>
                <script type="application/javascript" src="{% static 'reimbursement/js/scripts.js' %}"></script>
            </section>
        </div>
    <object class="object only-desktop" data="{% static 'reimbursement/svg/Topup-credit-bro.svg' %}" type="image/svg+xml"></object>
    </div>
{% endblock content %}